use_frameworks!

platform :ios, '9.0'

target 'Twirl_Example' do
  pod 'Twirl', :path => '../'

  target 'Twirl_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 3.1.2'
    pod 'Nimble', '~> 9.0.0'
  end
end
